### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by ericmelvin** [jakesherman/fonoapi#1]
I am receving the following error when trying to run the first example.  I have installed the module through pip.  

    from fonoapi import FonoAPI
ImportError: cannot import name 'FonoAPI'

**Comment by jakesherman** [comment]
Hi @ericmelvin, thanks for flagging! Let me take a look today. What version of Python are you using?

**Comment by viarurla** [comment]
Unsure if a related issue, but the import was failing for me for the Devices class.
`ImportError: cannot import name 'Devices' from 'fonoapi
`
I looked inside the __init__.py file and was able to rectify the issue by referencing the current package with a period to preface "fonoapi":
`from .fonoapi import (
    Devices,
    FonoAPI,
    InvalidAPITokenException,
    NoAPIResultsException,
    StatusCodeError200Exception,
    StatusCodeErrorNon200Exception
)`
Hope this is helpful in any way!

**Comment by jakesherman** [comment]
Sorry for taking so long to fix this, but it is now fixed in `v0.1.4`, which is available here on Github as well as on PyPI.
